# The URL the site will be built for
base_url = "https://colorlessred.github.io/blog-private/"

compile_sass = true
title = "even theme"
description = ""
highlight_code = true
generate_feed = true

[extra]